<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<form id="respond" method="post" action="<?php echo $this->getCommentFormAction() ?>">
	<div class="display-none">
		<input type="hidden" name="comment_post_ID" value="<?php echo $this->getPostId() ?>"/>
		<input type="hidden" name="comment_parent" id="comment_parent" value="<?php echo (int)$this->getRequest()->getParam('replytocom', 0) ?>"/>
	</div>
    <div class="title"><?php echo $this->__('Comments') ?></div>
    <?php if ($this->customerMustLogin()): ?>
        <p><?php echo $this->__('Sorry, you must be logged in to post a comment.') ?></p>
        <p><button class="button btn-login" type="button" onclick="setLocation('<?php echo $this->getLoginLink() ?>');"><span><span><?php echo $this->__('Login') ?></span></span></button></p>
    <?php else: ?>
        <ul class="form-list">
            <li class="wide media">
                <span class="author-img img pull-left"><img src="<?php echo $this->getSkinUrl().'images/comment-default-avatar.jpg'?>"/> </span>
                <div class="media-body">
                    <div class="input-box-comment">
                        <textarea id="comment" name="comment" rows="3" cols="45" class="required-entry"></textarea>
                    </div>
                    <?php if (!$this->isCustomerLoggedIn()): ?>
                    <div class="input-box-author">
                        <label for="author" class="required"><?php echo $this->__('Name') ?> <em>*</em></label>
                        <input type="text" id="author" name="author" class="input-text required-entry" value=""/>
                    </div>
                    <div class="input-box-email">
                        <label for="email" class="required"><?php echo $this->__('Email') ?> <em>*</em></label>
                        <input type="text" id="email" name="email" class="input-text required-entry validate-email" value=""/>
                    </div>
                    <?php endif; ?>
                    <div class="input-box-website">
                        <label for="url"><?php echo $this->__('Website') ?></label>
                        <input type="text" id="url" name="url" class="input-text" value=""/>
                    </div>
                    <?php if (!$this->customerMustLogin()): ?>
                        <div class="buttons-set">
                            <button type="submit" name="submit"  class="button btn btn-kid" value="Post your comment" id="post-the-comment">
                                <span><span><?php echo $this->__('Leave a comment') ?></span></span>
                            </button>
                            <span class="please-wait" id="respond-please-wait" style="display:none;">
                                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Please wait...') ?>" class="v-middle" /> <?php echo $this->__('Please wait...') ?>
                            </span>
                        </div>
                        <script type="text/javascript">
                            //<![CDATA[
                            var fishpigCommentsForm = {};
                            fishpigCommentsForm.url = '<?php echo $this->getPost()->getPermalink() ?>';
                            //]]>
                        </script>
                    <?php endif; ?>
                </div>
            </li>
            <?php echo $this->getChildHtml('before_form_end') ?>
        </ul>
    <?php endif; ?>
</form>