<div class="checkout">
    <div class="page-title">
        <h2><?php echo Mage::getStoreConfig('mtonestepcheckout/titles/checkout') ? Mage::getStoreConfig('mtonestepcheckout/titles/checkout') : $this->__('Checkout') ?></h2>
        <?php if (Mage::getStoreConfig('mtonestepcheckout/titles/checkout_sub')):?>
            <p><?php echo Mage::getStoreConfig('mtonestepcheckout/titles/checkout_sub')?></p>
        <?php endif ?>
        <?php if (!$this->isCustomerLoggedIn()):?>
            <p><a href="javascript:void(0)" onclick="mtOneStepCheckout.showLoginDialog('<h1><?php echo $this->__('Login')?></h1>', '<?php echo $this->__('Login')?>')"><?php echo $this->__('Already registered? Click here to login')?></a></p>
            <div id="checkout-login-form" style="display: none">
                <div id="checkout-login-error"></div>
                <div id="checkout-login-success"></div>
                <form method="post" action="<?php echo $this->getUrl('mtonestepcheckout/account/loginPost')?>" id="checkout-login">
                    <ul class="form-list">
                        <li>
                            <label for="login:username"><?php echo $this->__('Email address')?></label>
                            <input type="text" name="login[username]" id="login:username" class="input-text required-entry validate-email">
                        </li>
                        <li>
                            <label for="login:password"><?php echo $this->__('Password')?></label>
                            <input type="password" name="login[password]" id="login:pass" class="input-text required-entry">
                        </li>
                        <li>
                            <label>&nbsp;</label>
                            <a href="javascript:void(0)" onclick="mtOneStepCheckout.showForgot()"><?php echo $this->__('Forgot your password?')?></a>
                        </li>
                    </ul>
                </form>
                <form method="post" action="<?php echo $this->getUrl('mtonestepcheckout/account/forgotPasswordPost')?>" id="checkout-forgot" style="display: none">
                    <ul class="form-list">
                        <li>
                            <label for="login:email"><?php echo $this->__('Email address')?></label>
                            <input type="text" name="login[email]" id="login:email" class="input-text required-entry validate-email">
                        </li>
                        <li>
                            <label>&nbsp;</label>
                            <a href="javascript:void(0)" onclick="mtOneStepCheckout.showLogin()"><?php echo $this->__('Login')?></a>
                        </li>
                    </ul>
                </form>
                <div id="checkout-login-loading" style="display: none">
                    <img src="<?php echo Mage::getUrl('js')?>mt/onestepcheckout/images/rule-ajax-loader.gif"/>
                </div>
            </div>
        <?php endif ?>
    </div>
    <?php foreach ($this->getSteps() as $step=>$title) $titles[$step] = $title; ?>
    <?php $i=1 ?>
    <ol class="opc" id="checkoutSteps">
        <li class="col-lg-4">
            <ul>
                <?php if ($this->getChild('billing')->isShow()):?>
                <li>
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <span class="label label-warning"><?php echo $i++?></span>
                            <?php echo $titles['billing']['label']?>
                        </div>
                        <div id="checkout-step-billing" class="panel-body">
                            <?php echo $this->getChildHtml('billing') ?>
                        </div>
                    </div>
                </li>
                <?php endif ?>
                <?php if ($this->getChild('shipping')->isShow()):?>
                <li>
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <span class="label label-warning"><?php echo $i++?></span>
                            <?php echo $titles['shipping']['label']?>
                        </div>
                        <div id="checkout-step-shipping" class="panel-body">
                            <?php echo $this->getChildHtml('shipping') ?>
                        </div>
                    </div>
                </li>
                <?php endif ?>
            </ul>
        </li>
        <li class="col-lg-4">
            <ul>
                <?php if ($this->getChild('shipping_method')->isShow()):?>
                <li>
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <span class="label label-warning"><?php echo $i++?></span>
                            <?php echo $titles['shipping_method']['label']?>
                        </div>
                        <div id="checkout-step-shipping_method" class="panel-body">
                            <?php echo $this->getChildHtml('shipping_method') ?>
                        </div>
                    </div>
                </li>
                <?php endif ?>
                <?php if ($this->getChild('payment')->isShow()):?>
                <li>
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <span class="label label-warning"><?php echo $i++?></span>
                            <?php echo $titles['payment']['label']?>
                        </div>
                        <div id="checkout-step-payment" class="panel-body">
                            <?php echo $this->getChildHtml('payment') ?>
                        </div>
                    </div>
                </li>
                <?php endif ?>
            </ul>
        </li>
        <li class="col-lg-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <span class="label label-warning"><?php echo $i++?></span>
                    <?php echo $titles['review']['label']?>
                </div>
                <div id="checkout-step-review" class="panel-body">
                    <?php echo $this->getChildHtml('review') ?>
                </div>
            </div>
        </li>
    </ol>
</div>
<style type="text/css">
    #nprogress .bar {background: #<?php echo Mage::getStoreConfig('mtonestepcheckout/settings/bar_color')?>;}
</style>
<script type="text/javascript">
    var checkoutConfig = {
        showLoading: '<?php echo Mage::getStoreConfig('mtonestepcheckout/settings/bar')?>',
        loader: '<?php echo Mage::getStoreConfig('mtonestepcheckout/settings/loader') ? Mage::getBaseUrl('media').'mtonestepcheckout/'.Mage::getStoreConfig('mtonestepcheckout/settings/loader') : ''?>',
        cart: 'submitCartForm',
        cartRemoveUrl: '<?php echo $this->getUrl('mtonestepcheckout/cart/delete')?>',
        orderUrl: '<?php echo $this->getUrl('mtonestepcheckout/order/submit')?>',
        successUrl: '<?php echo $this->getUrl('checkout/onepage/success')?>',
        failureUrl: '<?php echo $this->getUrl('checkout/onepage/failure')?>'
    };
</script>