<div class="checkout">
    <div class="page-title">
        <h2><?php echo Mage::getStoreConfig('mtonestepcheckout/titles/checkout') ? Mage::getStoreConfig('mtonestepcheckout/titles/checkout') : $this->__('Checkout') ?></h2>
        <?php if (Mage::getStoreConfig('mtonestepcheckout/titles/checkout_sub')):?>
            <p><?php echo Mage::getStoreConfig('mtonestepcheckout/titles/checkout_sub')?></p>
        <?php endif ?>
        <?php if (!$this->isCustomerLoggedIn()):?>
            <!--p>
                <a href="#" data-toggle="modal" data-target="#checkout-login-dialog">
                    <?php echo $this->__('Already registered? Click here to login')?>
                </a>
            </p-->
            <div id="checkout-login-dialog" class="modal fade" role="dialog">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h3 class="modal-title"><?php echo $this->__('Login')?></h3>
                    </div>
                    <div class="modal-body">
                        <div class="alert alert-success hidden"></div>
                        <div class="alert alert-danger hidden"></div>
                        <form method="post" action="<?php echo $this->getUrl('mtonestepcheckout/account/loginPost')?>" id="checkout-login-form" class="form-horizontal" role="form">
                            <div class="form-group">
                                <label for="login:username" class="control-label col-sm-4"><?php echo $this->__('Email address')?></label>
                                <div class="col-sm-8">
                                    <input type="text" name="login[username]" id="login:username" class="form-control required-entry validate-email">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="login:password" class="control-label col-sm-4"><?php echo $this->__('Password')?></label>
                                <div class="col-sm-8">
                                    <input type="password" name="login[password]" id="login:password" class="form-control required-entry">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-8 col-sm-offset-4">
                                    <a href="javascript:void(0)" onclick="mtOneStepCheckout.showForgotForm()"><?php echo $this->__('Forgot your password?')?></a>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-4 col-sm-8">
                                    <button type="button" class="btn btn-kid" onclick="mtOneStepCheckout.login(this)"><?php echo $this->__('Login')?></button>
                                    <span class="checkout-login-loading hidden">
                                        <img src="<?php echo Mage::getUrl('js')?>mt/onestepcheckout/images/rule-ajax-loader.gif"/>
                                    </span>
                                </div>
                            </div>
                        </form>
                        <form method="post" action="<?php echo $this->getUrl('mtonestepcheckout/account/forgotPasswordPost')?>" id="checkout-forgot-form" class="hidden form-horizontal" role="form">
                            <div class="form-group">
                                <label for="login:email" class="control-label col-sm-4"><?php echo $this->__('Email address')?></label>
                                <div class="col-sm-8">
                                    <input type="text" name="login[email]" id="login:email" class="form-control required-entry validate-email">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-8 col-sm-offset-4">
                                    <a href="javascript:void(0)" onclick="mtOneStepCheckout.showLoginForm()"><?php echo $this->__('Login')?></a>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-4 col-sm-8">
                                    <button type="button" class="btn btn-kid" onclick="mtOneStepCheckout.login(this)"><?php echo $this->__('Send')?></button>
                                    <span class="checkout-login-loading hidden">
                                        <img src="<?php echo Mage::getUrl('js')?>mt/onestepcheckout/images/rule-ajax-loader.gif"/>
                                    </span>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                </div>
            </div>
        <?php endif ?>
    </div>
    <?php foreach ($this->getSteps() as $step=>$title) $titles[$step] = $title; ?>
    <?php $i=1 ?>
    <ol class="opc" id="checkoutSteps">
        <li class="col-lg-4 col-md-4  col-sm-4  col-xs-12">
            <ul>
                <?php if ($this->getChild('billing')->isShow()):?>
                <li>
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <span class="label label-warning"><?php echo $i++?></span>
                            <?php echo $titles['billing']['label']?>
                        </div>
                        <div id="checkout-step-billing" class="panel-body">
                            <?php echo $this->getChildHtml('billing') ?>
                        </div>
                    </div>
                </li>
                <?php endif ?>
                <?php if ($this->getChild('shipping')->isShow()):?>
                <li>
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <span class="label label-warning"><?php echo $i++?></span>
                            <?php echo $titles['shipping']['label']?>
                        </div>
                        <div id="checkout-step-shipping" class="panel-body">
                            <?php echo $this->getChildHtml('shipping') ?>
                        </div>
                    </div>
                </li>
                <?php endif ?>
            </ul>
        </li>
        <li class="col-lg-4 col-md-4  col-sm-4  col-xs-12">
            <ul>
                <?php if ($this->getChild('shipping_method')->isShow()):?>
                <li>
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <span class="label label-warning"><?php echo $i++?></span>
                            <?php echo $titles['shipping_method']['label']?>
                        </div>
                        <div id="checkout-step-shipping_method" class="panel-body">
                            <?php echo $this->getChildHtml('shipping_method') ?>
                        </div>
                    </div>
                </li>
                <?php endif ?>
                <?php if ($this->getChild('payment')->isShow()):?>
                <li>
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <span class="label label-warning"><?php echo $i++?></span>
                            <?php echo $titles['payment']['label']?>
                        </div>
                        <div id="checkout-step-payment" class="panel-body">
                            <?php echo $this->getChildHtml('payment') ?>
                        </div>
                    </div>
                </li>
                <?php endif ?>
            </ul>
        </li>
        <li class="col-lg-4 col-md-4  col-sm-4  col-xs-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <span class="label label-warning"><?php echo $i++?></span>
                    <?php echo $titles['review']['label']?>
                </div>
                <div id="checkout-step-review" class="panel-body">
                    <?php echo $this->getChildHtml('review') ?>
                </div>
            </div>
        </li>
    </ol>
</div>
<style type="text/css">
    #nprogress .bar {background: #<?php echo Mage::getStoreConfig('mtonestepcheckout/settings/bar_color')?>;}
</style>
<script type="text/javascript">
    var checkoutConfig = {
        showLoading: '<?php echo Mage::getStoreConfig('mtonestepcheckout/settings/bar')?>',
        loader: '<?php echo Mage::getStoreConfig('mtonestepcheckout/settings/loader') ? Mage::getBaseUrl('media').'mtonestepcheckout/'.Mage::getStoreConfig('mtonestepcheckout/settings/loader') : ''?>',
        cart: 'submitCartForm',
        cartRemoveUrl: '<?php echo $this->getUrl('mtonestepcheckout/cart/delete')?>',
        orderUrl: '<?php echo $this->getUrl('mtonestepcheckout/order/submit')?>',
        successUrl: '<?php echo $this->getUrl('checkout/onepage/success')?>',
        failureUrl: '<?php echo $this->getUrl('checkout/onepage/failure')?>'
    };
</script>