<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
$attributes = $this->getAttibuteOptions();
$id         = $this->getConfig('id');
$column     = $this->getConfig('column');
$scroll     = $this->getConfig('scroll');
$title      = $this->getConfig('widget_title');
?>
<?php if ($scroll == 1):?>
    <script type="text/javascript">
        <?php echo $id?> = {
            responsive: <?php echo $this->getConfig('responsive')?>,
            config: {
                namespace: '<?php echo $this->getConfig('namespace')?>',
                slideshow: <?php echo $this->getConfig('autoplay')?>,
                slideshowSpeed: <?php echo $this->getConfig('speed')?>,
                animationLoop: <?php echo $this->getConfig('loop')?>,
                controlNav: false,
                directionNav: false,
                itemMargin: <?php echo $this->getConfig('margin')?>,
                move: <?php echo $this->getConfig('move')?>,
                start: function(e){
                    jQuery('.btn-prev', e).click(function(){
                        e.flexAnimate(e.getTarget("prev"), true);
                    });
                    jQuery('.btn-next', e).click(function(){
                        e.flexAnimate(e.getTarget("next"), true);
                    });
                }
            }
        };
    </script>
<?php endif ?>
<div class="slider-attribute-wrapper<?php echo $scroll==1 ? ' flexslider' : ''?>" id="<?php echo $id ?>">
    <?php if ($title):?>
        <button class="btn-widget btn btn-kid" type="button"><?php echo $title?></button>
    <?php endif ?>
    <div class="btn-group">
        <a class="btn btn-default btn-prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
        <a class="btn btn-default btn-next"><i class="glyphicon glyphicon-chevron-right"></i></a>
    </div>
    <ul class="slides">
        <?php foreach ($attributes as $attribute): ?>
            <li class="slide">
                <a href="<?php echo $attribute['link'] ?>" title="<?php echo Mage::helper('mtwidget')->__('%s', $attribute['label']) ?>">
                    <img src="<?php echo strpos($attribute['image'], 'http') === 0 ? $attribute['image'] : Mage::getBaseUrl('media') . $attribute['image'] ?>" alt="<?php echo $attribute['label'] ?>" />
                </a>
            </li>
        <?php endforeach ?>
    </ul>
</div>