<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
/* @var $this MT_Widget_Block_WIdget */
$attributes = $this->getAttibuteOptions();
$id         = $this->getConfig('id');
$scroll     = $this->getConfig('scroll');
$title      = $this->getConfig('widget_title');
/* @var $category Mage_Catalog_Model_Category */
$category   = Mage::registry('current_category');
?>
<?php if (!$this->getRequest()->isXmlHttpRequest()): ?>
<?php if ($category && $category->hasChildren()): ?>
<?php if (count($attributes)): ?>
<?php if ($scroll == 1): ?>
    <script type="text/javascript">
        <?php echo $id ?> = {
            items: <?php echo $this->getConfig('items') ?>,
            autoPlay: <?php echo $this->getConfig('autoplay') ?>,
            pagination: <?php echo $this->getConfig('paging') ?>,
            afterInit: function(slider){
                var parent = jQuery(slider).parent();
                jQuery('.btn-prev', parent).click(function(){
                    jQuery(slider).data('owlCarousel').prev();
                });
                jQuery('.btn-next', parent).click(function(){
                    jQuery(slider).data('owlCarousel').next();
                });
            }
        };
    </script>
<?php endif ?>
<div class="<?php echo $this->getConfig('classes')?> attribute-carousel-wrapper">
    <?php if ($title): ?>
        <h3 class="utm-cookies"><?php echo $title ?></h3>
    <?php endif ?>
    <ul class="grid-6 slider-attribute-wrapper <?php echo $scroll==1 ? 'owl-carousel' : '' ?>" id="<?php echo $id ?>">
        <?php $i=0; foreach ($attributes as $attribute): ?>
            <li class="item-<?php echo $i++ ?> attribute-brands">
                <a href="<?php echo $attribute['link'] ?>" title="<?php echo Mage::helper('mtwidget')->__('%s', $attribute['label']) ?>">
                    <img src="<?php echo strpos($attribute['image'], 'http') === 0 ? $attribute['image'] : Mage::helper('kidsplaza')->resize(Mage::getBaseDir('media') .DS. $attribute['image'], 80) ?>" alt="<?php echo $attribute['label'] ?>" />
                </a>
            </li>
        <?php endforeach ?>
    </ul>
</div>
<?php endif ?>
<?php endif ?>
<?php endif ?>