<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2014 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
/* @var $this MT_Widget_Block_Widget */
$blogs      = $this->getBlogs();
$id         = $this->getConfig('id');
$title      = $this->getConfig('widget_title');
?>
<div class="widget widget-blogs">
<?php if ($title):?>
<h3><?php echo $title ?></h3>
<?php endif ?>
<ul class="block-blogs <?php echo $this->getConfig('classes')?>">
    <?php $i=0; foreach ($blogs as $blog):?>
        <?php /* @var $blog Fishpig_Wordpress_Model_Post */ ?>
        <li class="item-<?php echo $i++ ?>">
            <a class="img" href="<?php echo $blog->getUrl() ?>">
                <img src="<?php echo $blog->getFeaturedImage() ? $blog->getFeaturedImage()->getThumbnailImage() : Mage::helper('kidsplaza')->resize('tmp/nofile', 50) ?>" width="50"/>
            </a>
            <div class="right-blogs">
               <a href="<?php echo $blog->getUrl() ?>"><?php echo $blog->getPostTitle() ?></a>
                <?php if ($blog->getPostTime()): ?>
                    <i class="glyphicon glyphicon-calendar"></i>
                    <span><?php echo $blog->getPostTime('d/m/Y') ?></span>
                <?php endif ?>
            </div>
        </li>
    <?php endforeach ?>
</ul>
</div>