<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Review
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
?>
<div class="form-add row">
    <span class="your-review"><?php echo Mage::helper('mtreview')->__('Write Your Own Review') ?></span>
    <?php if ($this->getAllowWriteReviewFlag()): ?>
    <form action="<?php echo $this->getAction() ?>" method="post" id="review-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <fieldset>
            <?php echo $this->getChildHtml('form_fields_before')?>
            <h3><?php echo Mage::helper('mtreview')->__("You're reviewing:"); ?> <span><?php echo $this->escapeHtml($this->getProductInfo()->getName()) ?></span></h3>
            <?php if( $this->getRatings() && $this->getRatings()->getSize()): ?>
                <span class="how-do"><?php echo Mage::helper('mtreview')->__('How do you rate this product?') ?> <em class="required">*</em></span>
                <span id="input-message-box"></span>
                <div id="product-review-table" class="review-rating">
                    <div class="rating-type-item"></div>
                    <?php $i = 0;foreach ($this->getRatings() as $_rating): ?>
                        <div class="rating-type-item">
                            <!--span class="rating-type"><?php echo $this->escapeHtml($_rating->getRatingCode()) ?></span-->
                            <?php foreach ($_rating->getOptions() as $_option): ?>
                            <input style="display: none;" type="radio" name="ratings[<?php echo $_rating->getId() ?>]" id="<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>" value="<?php echo $_option->getId() ?>" class="rating-star radio" />
                            <?php endforeach; ?>
                        </div>
                    <?php $i++; endforeach; ?>
                </div>
                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
            <?php endif; ?>
                <div class="form-list media">
                    <span class="author-img img pull-left"><img src="<?php echo $this->getSkinUrl().'images/comment-default-avatar.jpg'?>"/> </span>
                    <div class="media-body">
                        <textarea name="detail" id="review_field" cols="5" rows="3" class="required-entry form-control" placeholder="<?php echo $this->__('Enter your review');?>"><?php echo $this->escapeHtml($data->getDetail()) ?></textarea>
                        <div class="form-field">
                            <div class="input-box">
                                <label for="summary_field"><?php echo $this->__('Summary of Your Review') ?></label>
                                <input type="text" name="title" id="summary_field" class="input-text form-control" value="<?php echo $this->escapeHtml($data->getTitle()) ?>" />
                            </div>
                            <div class="input-box">
                                <label for="nickname_field" class="required"><em>*</em><?php echo $this->__('Nickname') ?></label>
                                <input type="text" name="nickname" id="nickname_field" class="input-text required-entry form-control" value="<?php echo $this->escapeHtml($data->getNickname()) ?>" />
                            </div>
                            <div class="buttons-set">
                                <button type="submit" title="<?php echo Mage::helper('mtreview')->__('Submit Review') ?>" class="button btn-kid btn"><span><span><?php echo Mage::helper('mtreview')->__('Submit Review');?></span></span></button>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        reviewFrom = {};
        reviewFrom.msg = '<?php echo $this->__('Please select one of each of the ratings above') ?>';
        //]]>
    </script>
    <?php else: ?>
    <p class="review-nologged" id="review-form">
        <?php echo Mage::helper('mtreview')->__('Only registered users can write reviews. Please, <a href="%s">log in</a> or <a href="%s">register</a>', $this->getLoginLink(), Mage::helper('customer')->getRegisterUrl()) ?>
    </p>
    <?php endif ?>
</div>
