<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Review
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
?>
<?php if(!empty($collection) && $collection->getSize()): ?>
    <div class="ratings-table">
        <?php foreach ($collection as $_rating): ?>
            <?php if($_rating->getSummary()): ?>
                <div class="rating-item">
                    <div class="rating-name"><?php echo $this->__($this->escapeHtml($_rating->getRatingCode())) ?></div>
                    <div class="all-total">
                        <?php echo $total = round(($_rating->getSummary()*5)/100,1);?>/5
                    </div>
                    <div class="rating-box">
                        <div class="rating" style="width:<?php echo ceil($_rating->getSummary()) ?>%;"></div>
                    </div>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>