<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Review
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
?>
<div class="mt-reply">
    <a onclick="return showComment(this)" class="btn-reply" data-form="commnet_field_<?php echo $this->getReviewId();?>" href="javascript:void(0)">
        <i class="glyphicon glyphicon-comment"></i>
        <?php echo Mage::helper('mtreview')->__('Reply') ?>
    </a>
</div>
<script type="text/javascript">
    var Comment = {};
    Comment.link = '<?php echo $this->getReplyUrl();?>';
</script>