<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Review
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
$helper = Mage::helper('mtreview');
?>
<span class="mt-report">
    <?php if(!$helper->isReportRegistered($this->getReviewId())):?>
        <a href="<?php echo $this->getReportUrl();?>" onclick="return reportReview(this)" class="report-it"><?php echo Mage::helper('mtreview')->__('Report');?></a>
    <?php else:?>
        <span class="mt-reported"><?php echo Mage::helper('mtreview')->__('Reported');?></span>
    <?php endif;?>
</span>