<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<div class="post-list-item">
	<?php echo $this->getBeforePostContentHtml() ?>
	<div class="post-entry media">
		<?php if ($post->isViewableForVisitor()): ?>
			<?php if ($featuredImage = $post->getFeaturedImage()): ?>
				<span class="featured-image left pull-left">
					<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>">
                        <img src="<?php echo $featuredImage->getAvailableImage() ?>" width="90" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/>
                    </a>
				</span>
			<?php endif; ?>
                <div class="media-body">
                    <div class="postTitle">
                        <span class="title"><h3><a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><?php echo $this->escapeHtml($post->getPostTitle()) ?></a></h3></span>
                        <span class="created">
                            <?php echo $this->getAfterPostContentHtml() ?>
                        </span>
                        <div class="postContent">
                            <?php if ($this->displayExcerptInFeed() || $post->hasMoreTag()): ?>
                                <?php echo $post->getPostExcerpt() ?>
                            <?php else: ?>
                                <?php echo $post->getPostContent() ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
		<?php else: ?>
			<?php echo $this->getPasswordProtectHtml($post) ?>
		<?php endif; ?>
	</div>
</div>