<?php
/**
 * @category    MT
 * @package     MT_KidsPlaza
 * @copyright   Copyright (C) 2014 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<tr>
    <td class="label"><?php echo $this->getElement()->getLabel() ?></td>
    <td class="grid" style="">
        <table cellspacing="0" class="data border" id="<?php echo $this->getElement()->getHtmlId() ?>">
            <colgroup>
                <col width="400"/>
                <col width=""/>
            </colgroup>
            <thead>
                <tr class="headings">
                    <th><?php echo Mage::helper('revslider')->__('Youtube Url')?></th>
                    <th><?php echo Mage::helper('revslider')->__('Action')?></th>
                </tr>
            </thead>
            <tbody id="<?php echo $this->getElement()->getHtmlId() ?>_container"></tbody>
            <tfoot>
                <td colspan="2" class="a-right"><?php echo $this->getAddButtonHtml() ?></td>
            </tfoot>
        </table>
        <?php if ($note = $this->getElement()->getNote()):?>
        <p class="note" id="note_delay">
            <span><?php echo $note?></span>
        </p>
        <?php endif?>
    </td>
</tr>
<script type="text/javascript">
    var videoRowTemplate = '<tr id="video-{{id}}">'+
        '<td><input type="text" class="input-text" style="width:98%;" value="{{link}}" name="videos[]"/>'+
        '<td><?php echo $this->getDeleteButtonHtml()?></td>'+
        '</tr>';

    window.videoForm = {
        template: new Template(videoRowTemplate, new RegExp('(^|.|\\r|\\n)({{\\s*(\\w+)\\s*}})', "")),
        itemsCount: 0,
        container: $('<?php echo $this->getElement()->getHtmlId() ?>_container'),
        add: function(link){
            var data = {
                link: link || '',
                id: ++this.itemsCount
            };
            this.container.insert({bottom :this.template.evaluate(data)});
        },
        remove: function(id){
            var tr = this.container.down('tr#video-' + id);
            if (tr) tr.remove();
        }
    };

    <?php foreach ($this->getVideos() as $video):?>
    videoForm.add(<?php echo json_encode($video) ?>);
    <?php endforeach ?>
</script>