<?php
/**
 * @category    MT
 * @package     MT_Location
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<div class="col-lg-4">
    <ul class="locations" id="locations" style="max-height: 450px;"></ul>
</div>
<div class="col-lg-8">
    <div id="location_map" style="height: 450px;"></div>
</div>