<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Review
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
?>
<h2><?php echo $this->__('Customer Reviews') ?></h2>
<div class="mt-review-main">
    <?php if(count($this->getReviewsCollection()->getItems())>0){?>
        <div class="summary-review row show-grid">
            <?php echo $this->getChildHtml('summary_reviews'); ?>
        </div>
    <?php }?>
    <?php echo $this->getChildHtml('review_form') ?>
</div>
<?php $_items = $this->getReviewsCollection()->getItems();?>
<div class="box-collateral box-reviews" id="customer-reviews">
    <?php if (count($_items)):?>
        <?php echo $this->getChildHtml('review_ordering') ?>
        <ul>
        <?php foreach ($_items as $_review):?>
            <li class="media">
                <span class="img pull-left">
                     <img src="<?php echo $this->getSkinUrl().'images/list_avatar_question.png'?>"/>
                </span>
                <div class="media-body">
                    <span class="main-review">
                        <span class="rating-summary">
                            <?php $_votes = $_review->getRatingVotes(); ?>
                            <?php if (count($_votes)): ?>
                                <?php foreach ($_votes as $_vote): ?>
                                    <div class="rating-box">
                                        <div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
                                    </div>
                                <?php endforeach; ?>
                            <?php endif; ?>
                            <span class="summary"><?php echo $this->escapeHtml($_review->getTitle()) ?></span>
                            <span class="total-comment"><i><?php echo $this->__('%s Comment',$this->getTotalComments($_review->getId()));?></i></span>
                            <span class="report">
                                <?php
                                    if($this->showReport()){
                                        echo $this->getChild('mtreview_report')->setReviewId($_review->getId())->toHtml();
                                    }
                                ?>
                            </span>
                        </span>
                        <span class="created_by">
                            <?php echo $this->__('<span class="created">%s</span>', $this->escapeHtml($_review->getNickname())) ?>
                            <small class="date"><?php echo $this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt()), 'long') ?></small>
                        </span>
                    </span>
                    <span class="review-detail"><?php echo nl2br($this->escapeHtml($_review->getDetail())) ?></span>
                    <span class="review-footer">
                        <?php echo $this->getChild('mtreview_footer')->setReviewId( $_review->getId() )->toHtml();?>
                    </span>
                </div>
            </li>
        <?php endforeach; ?>
        </ul>
        <?php echo $this->getBlockHtml('formkey'); ?>
        <?php echo $this->getChildHtml('review_ordering') ?>
        <?php echo $this->getChildHtml('toolbar') ?>
    <?php endif;?>
</div>
