<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Review
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
?>
<div class="sorter">
    <div class="sort-by">
        <label><?php echo Mage::helper('mtreview')->__('Sort By') ?></label>
        <select onchange="setLocation(this.value)">
            <?php foreach($this->getAvailableOrders() as $item): ?>
                <option value="<?php echo $this->getOrderUrl($item['value'], 'asc') ?>"<?php if($this->isOrderCurrent($item['value'])): ?> selected="selected"<?php endif; ?>>
                    <?php echo $this->__($item['label']) ?>
                </option>
            <?php endforeach; ?>
        </select>
        <?php if($this->getCurrentDirection() == 'desc'): ?>
            <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/i_desc_arrow.gif') ?>" alt="<?php echo $this->__('Set Ascending Direction') ?>" class="v-middle" /></a>
        <?php else: ?>
            <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/i_asc_arrow.gif') ?>" alt="<?php echo $this->__('Set Descending Direction') ?>" class="v-middle" /></a>
        <?php endif; ?>
    </div>
    <?php echo $this->getChildHtml('toolbar_pager'); ?>
</div>
