<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Review
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
$summarys = $this->getSummaryBlock();
$product = $this->getProduct();
?>
<?php if(is_array($summarys)):?>
    <div class="review-sum-total col-md-4">
        <div class="average-rating">
            <h3><?php echo $this->__('Average Rating')?></h3>
            <?php echo $this->getReviewsSummaryHtml()?>
        </div>
        <?php
        $i=0;
        foreach($summarys as $summary):?>
            <?php if($summary['votes_qty']>0):?>
            <p><?php echo $this->__('(Total: %s Reviews)', $summary['votes_qty']);?></p>
                <?php endif;?>
        <?php $i++;
        endforeach;?>
    </div>
    <div class="rating-summary-block col-md-5">
        <?php foreach($summarys as $summary):?>
            <?php if($summary['votes_qty'] > 0):?>
                <div class="main-progress">
                    <span class="rating-name"><?php echo $summary['name']?></span>
                    <div class="review-rating-total">
                        <div class="rating-num"><?php echo $this->__('5 star');?>: </div>
                        <div class="progress">
                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<?php echo isset($summary['votes'][5]['percent']) ? $summary['votes'][5]['percent'] : ''?>" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo isset($summary['votes'][5]['percent']) ? $summary['votes'][5]['percent'] : ''?>%">
                                <span class="sr-only"><?php echo isset($summary['votes'][5]['percent']) ? $summary['votes'][5]['percent'] : ''?>%</span>
                            </div>
                        </div>
                        <div class="rating-num-total"><?php echo isset($summary['votes'][5]['qty']) ? $summary['votes'][5]['qty'] : 0?></div>
                    </div>
                    <div class="review-rating-total">
                        <div class="rating-num"><?php echo $this->__('4 star');?>: </div>
                        <div class="progress">
                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<?php echo isset($summary['votes'][4]['percent']) ? $summary['votes'][4]['percent'] : ''?>" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo isset($summary['votes'][4]['percent']) ? $summary['votes'][4]['percent'] : ''?>%">
                                <span class="sr-only"><?php echo isset($summary['votes'][4]['percent']) ? $summary['votes'][4]['percent'] : ''?>%</span>
                            </div>
                        </div>
                        <div class="rating-num-total"><?php echo isset($summary['votes'][4]['qty']) ? $summary['votes'][4]['qty'] : 0?></div>
                    </div>
                    <div class="review-rating-total">
                        <div class="rating-num"><?php echo $this->__('3 star');?>: </div>
                        <div class="progress">
                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<?php echo isset($summary['votes'][3]['percent']) ? $summary['votes'][3]['percent'] : ''?>" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo isset($summary['votes'][3]['percent']) ? $summary['votes'][3]['percent'] : ''?>%">
                                <span class="sr-only"><?php echo isset($summary['votes'][3]['percent']) ? $summary['votes'][3]['percent'] : ''?>%</span>
                            </div>
                        </div>
                        <div class="rating-num-total"><?php echo isset($summary['votes'][3]['qty']) ? $summary['votes'][3]['qty'] : 0?></div>
                    </div>
                    <div class="review-rating-total">
                        <div class="rating-num"><?php echo $this->__('2 star');?>: </div>
                        <div class="progress">
                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<?php echo isset($summary['votes'][2]['percent']) ? $summary['votes'][2]['percent'] : ''?>" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo isset($summary['votes'][2]['percent']) ? $summary['votes'][2]['percent'] : ''?>%">
                                <span class="sr-only"><?php echo isset($summary['votes'][2]['percent']) ? $summary['votes'][2]['percent'] : ''?>%</span>
                            </div>
                        </div>
                        <div class="rating-num-total"><?php echo isset($summary['votes'][2]['qty']) ? $summary['votes'][2]['qty'] : 0?></div>
                    </div>
                    <div class="review-rating-total">
                        <div class="rating-num"><?php echo $this->__('1 star');?>: </div>
                        <div class="progress">
                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<?php echo isset($summary['votes'][1]['percent']) ? $summary['votes'][1]['percent'] : ''?>" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo isset($summary['votes'][1]['percent']) ? $summary['votes'][1]['percent'] : ''?>%">
                                <span class="sr-only"><?php echo isset($summary['votes'][1]['percent']) ? $summary['votes'][1]['percent'] : ''?>%</span>
                            </div>
                        </div>
                        <div class="rating-num-total"><?php echo isset($summary['votes'][1]['qty']) ? $summary['votes'][1]['qty'] : 0?></div>
                    </div>
                </div>
            <?php endif;?>
        <?php endforeach;?>
    </div>
    <div class="col-md-3">
        <div class="write-review-button">
            <button type="button" class="rating-form btn btn-kid"><?php echo $this->__('Write Review');?></button>
        </div>
    </div>
<?php endif;?>

