<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>

<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php if ($this->getChild('aw_blog_comments_toolbar')->getCurrentMode() == 'list'):?>
    <ul class="blog-list">
        <?php foreach ($posts as $post): ?>
            <li class="blog-item">
                <div class="postWrapper">
                    <div class="postTitle">
                        <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
                        <h3><?php echo $post->getCreatedTime(); ?></h3>
                    </div>
                    <div class="postContent"><?php echo $post->getPostContent(); ?></div>

                    <?php echo $this->getBookmarkHtml($post) ?>
                    <div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
                    <div class="postDetails">
                        <?php if ($this->getCommentsEnabled()): ?>
                            <?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Comments</a> |
                        <?php endif; ?>
                        <?php $postCats = $post->getCats(); ?>
                        <?php if (!empty($postCats)): ?>
                            <?php echo Mage::helper('blog')->__('Posted in'); ?>
                            <?php foreach ($postCats as $data): ?>
                                <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <?php echo Mage::helper('blog')->__('Posted'); ?>
                        <?php endif; ?><?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?></div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <?php $_collectionSize = $posts->count() ?>
    <?php $_columnCount = $this->getColumnCount() ? $this->getColumnCount() : 1; ?>
    <?php $i=0; foreach ($posts as $post): ?>
        <?php if ($i++ % $_columnCount == 0): ?>
            <ul class="blog-grid">
        <?php endif ?>
        <li class="blog-item">
            <div class="postWrapper">
                <div class="postTitle">
                    <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
                    <h3><?php echo $post->getCreatedTime(); ?></h3>
                </div>
                <div class="postContent"><?php echo $post->getPostContent(); ?></div>

                <?php echo $this->getBookmarkHtml($post) ?>
                <div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
                <div class="postDetails">
                    <?php if ($this->getCommentsEnabled()): ?>
                        <?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Comments</a> |
                    <?php endif; ?>
                    <?php $postCats = $post->getCats(); ?>
                    <?php if (!empty($postCats)): ?>
                        <?php echo Mage::helper('blog')->__('Posted in'); ?>
                        <?php foreach ($postCats as $data): ?>
                            <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <?php echo Mage::helper('blog')->__('Posted'); ?>
                    <?php endif; ?><?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?></div>
            </div>
        </li>
        <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
            </ul>
        <?php endif ?>
    <?php endforeach ?>
<?php endif ?>
<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
