<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<div class="main-post">
    <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
    <?php if ($this->getChild('aw_blog_comments_toolbar')->getCurrentMode() == 'list'):?>
        <ul class="blog-list">
            <?php foreach ($posts as $post): ?>
                <li class="blog-item media">
                    <span class="blog-img img pull-left">
                        <img src="<?php echo Mage::helper('kidsplaza')->resize(Mage::getBaseDir().'/media/'.$post->getThumb(), 90); ?>" alt="<?php echo $post->getTitle(); ?>" />
                    </span>
                    <div class="media-body">
                        <div class="postTitle">
                            <span class="title"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></span>
                            <span class="created"><?php echo date('d/m/Y - g:i a',strtotime($post->getCreatedTime())); ?></span>
                            <span class="comment-count">
                                <?php if ($this->getCommentsEnabled()): ?>
                                    <?php echo $post->getCommentCount() ? $post->getCommentCount() : 0; ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Comments</a>
                                <?php endif; ?>
                            </span>
                        </div>
                        <div class="postContent"><?php echo $post->getPostContent(); ?></div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <?php $_collectionSize = $posts->count() ?>
        <?php $_columnCount = $this->getColumnCount() ? $this->getColumnCount() : 1; ?>
        <div class="grid-view">
        <?php $i=0; foreach ($posts as $post): ?>
            <?php if ($i++ % $_columnCount == 0): ?>
                <ul class="blog-grid">
                    <?php endif ?>
                    <li class="blog-item media">
                        <span class="blog-img img pull-left">
                            <img src="<?php echo Mage::helper('kidsplaza')->resize(Mage::getBaseDir().'/media/'.$post->getThumb(), 90); ?>" alt="<?php echo $post->getTitle(); ?>" />
                        </span>
                        <div class="media-body">
                            <div class="postTitle">
                                <span class="title"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></span>
                                <span class="created"><?php echo date('d/m/Y - g:i a',strtotime($post->getCreatedTime())); ?></span>
                                <span class="comment-count">
                                    <?php if ($this->getCommentsEnabled()): ?>
                                        <?php echo $post->getCommentCount() ? $post->getCommentCount() : 0; ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Comments</a>
                                    <?php endif; ?>
                                </span>
                            </div>
                            <div class="postContent"><?php echo $post->getPostContent(); ?></div>
                        </div>
                    </li>
            <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                </ul>
            <?php endif ?>
        <?php endforeach ?>
        </div>
    <?php endif ?>
    <div class="load-more-posts">
        <span class="loading"><?php echo $this->__('Loading...');?></span><button class="btn btn-load-more"><?php echo $this->__('See More ');?></button>
    </div>
</div>
