<?php
/**
 * @category    MT
 * @package     KidsPlaza
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<div class="modal fade" id="location-modal" role="dialog">

    <div class="modal-dialog">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="modal-content">
            <div class="modal-header">

                <h4 class="modal-title"> <?php echo $this->__('Choose your location') ?> <i class="glyphicon glyphicon-map-marker"></i></h4>
            </div>
            <div class="modal-body">
                <?php foreach ($this->getWebsites() as $website): ?>
                    <a class="btn btn-login" href="#" onclick="return KPLocation.setLocation('<?php echo $website['code'] ?>')">
                        <?php echo $website['label'] ?>
                    </a>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>