<?php
/**
 * @category    MT
 * @package     KidsPlaza
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
/* @var $session Mage_Customer_Model_Session */
$session = Mage::getSingleton('customer/session');
?>
<div class="top-login pull-right">
        <div class="toplogin" id="topLogin">
            <div class="font"><i class="glyphicon glyphicon-user"></i></div>
            <div class="right-login">
                <?php if ($session->isLoggedIn()): ?>
                    <p><?php echo $session->getCustomer()->getName() ?></p>
                <?php else: ?>
                    <p><?php echo Mage::helper('kidsplaza')->__('Login') ?></p>
                <?php endif ?>
                <span><?php echo Mage::helper('kidsplaza')->__('Account and Orders') ?></span>
            </div>
        </div>
        <div class="login-content" style="display: none">
            <?php if (!$session->isLoggedIn()): ?>
                <button onclick="setLocation('<?php echo $this->getUrl('customer/account/login') ?>')" class="btn btn-login btn-signin">
                    <?php echo $this->__('Login') ?>
                </button>
                <p>
                    <span><?php echo Mage::helper('kidsplaza')->__('New customer?') ?></span>
                    <a href="<?php echo $this->getUrl('customer/account/login') ?>"><?php echo Mage::helper('kidsplaza')->__('Create account') ?></a>
                </p>
            <?php endif ?>
            <ul>
                <li>
                    <i class="glyphicon glyphicon-user"></i>
                    <a href="<?php echo $this->getUrl('customer/account') ?>"><?php echo Mage::helper('kidsplaza')->__('My account') ?></a>
                </li>
                <li>
                    <i class="glyphicon glyphicon-list-alt"></i>
                    <a href="<?php echo $this->getUrl('sales/order/history') ?>"><?php echo Mage::helper('kidsplaza')->__('My Orders') ?></a>
                </li>
                <li>
                    <i class="glyphicon glyphicon-heart"></i>
                    <a href="<?php echo $this->getUrl('wishlist') ?>"><?php echo Mage::helper('kidsplaza')->__('My Wishlist') ?></a>
                </li>
                <?php if ($session->isLoggedIn()): ?>
                <li>
                    <i class="glyphicon glyphicon-log-out"></i>
                    <a href="<?php echo $this->getUrl('customer/account/logout') ?>"><?php echo Mage::helper('kidsplaza')->__('Log out') ?></a>
                </li>
                <?php endif ?>
            </ul>
        </div>
</div>