<?php
/**
 * @category    MT
 * @package     KidsPlaza
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
/* @var $session Mage_Customer_Model_Session */
$session = Mage::getSingleton('customer/session');
?>
<div class="pull-right top-login" id="topLogin">
        <div  class="toplogin" href="javascript:void(0)">
            <div class="font"><i class="glyphicon glyphicon-user"></i></div>
            <div class="right-login">
                    <?php if ($session->isLoggedIn()): ?>
                    <?php echo $session->getCustomer()->getName() ?>
                    <?php else: ?>
                        <p><?php echo $this->__('Đăng Nhập') ?></p>
                        <span><?php echo $this->__('Tài khoản và Đơn hàng') ?></span>
                    <?php endif ?>
            </div>
        </div>
        <div class="login-content" style="display: none">
            <?php if (!$session->isLoggedIn()): ?>
                <button onclick="setLocation('<?php echo $this->getUrl('customer/account/login') ?>')" class="btn btn-login btn-signin">
                    <?php echo $this->__('Đăng Nhập') ?>
                </button>
                <p>
                    <span><?php echo $this->__('Khách hàng mới?') ?></span>
                    <a href="<?php echo $this->getUrl('customer/account/login') ?>"><?php echo $this->__('Tạo tài khoản') ?></a>
                </p>
            <?php endif ?>
            <ul>
                <li>
                    <i class="glyphicon glyphicon-user"></i>
                    <a href="<?php echo $this->getUrl('customer/account') ?>"><?php echo $this->__('My account') ?></a>
                </li>
                <li>
                    <i class="glyphicon glyphicon-list-alt"></i>
                    <a href="<?php echo $this->getUrl('sales/order/history') ?>"><?php echo $this->__('My Orders') ?></a>
                </li>
                <?php if ($session->isLoggedIn()): ?>
                <li>
                    <i class="glyphicon glyphicon-log-out"></i>
                    <a href="<?php echo $this->getUrl('customer/account/logout') ?>"><?php echo $this->__('Đăng Xuất ') ?></a>
                </li>
                <?php endif ?>
            </ul>
        </div>
</div>