<?php
/**
 * @category    MT
 * @package     KidsPlaza
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 *
 * @var $this Mage_Checkout_Block_Cart_Sidebar
 */
?>
<div class="vr"></div>
<div class="top-cart" id="cart-top" data-title="<?php echo Mage::helper('kidsplaza')->__('Recently added item(s)')?>">
    <span class="cart-icon"></span>
    <a class="cart-content hidden-sm hidden-md hidden-xs" href="javascript:void(0)">
        <?php echo Mage::helper('kidsplaza')->__('My Cart')?>
        <span class="cart-summary"><?php echo $this->__('%d product(s)', (int)$this->getSummaryCount()) ?></span>
    </a>
    <div class="cart-items" style="display: none">
        <?php $_items = $this->getRecentItems() ?>
        <?php if(count($_items)): ?>
            <ol class="mini-products-list">
                <?php foreach($_items as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach; ?>
            </ol>
            <div class="cart-action">
                <span class="cart-total pull-left"><?php echo $this->helper('checkout')->formatPrice($this->getSubtotal())?></span>
                <a href="<?php echo $this->getUrl('checkout/onepage')?>"><?php echo $this->__('Checkout')?>&nbsp;<i class="glyphicon glyphicon-chevron-right"></i></a>
            </div>
        <?php else: ?>
            <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
        <?php endif ?>
    </div>
</div>