<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Review
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
$_product = $this->getProduct();
?>
<div class="ratings">
    <div class="rating-box">
        <div class="rating" style="width:<?php echo $this->getRatingSummary()?$this->getRatingSummary():0 ?>%"></div>
    </div>
    <a class="rating-reviews" href="javascript:void(0)" onclick="jQuery('#product-review').scrollToMe()">
        <?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?>
    </a>
</div>
