<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Review
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
?>
<div class="ratings">
    <div class="rating-box">
        <div class="rating" style="width:<?php echo (int)$this->getRatingSummary() ?>%"></div>
    </div>
    <?php if ($this->getReviewsCount()): ?>
        <span class="amount"><?php echo $this->getReviewsCount() ?></span>
    <?php endif; ?>
</div>
