<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<?php $date = Mage::getModel('core/date') ?>
<?php if ($post): ?>
<?php if ($this->hasTags($post)): ?>
    <?php echo $date->date('d/m/Y - g:i a', strtotime($post->getPostDate('Y-m-d h:i:s'))); ?>
<?php else: ?>
    <?php echo $date->date('d/m/Y - g:i a', strtotime($post->getPostDate('Y-m-d h:i:s'))); ?>
<?php endif; ?>
<?php endif; ?>