<!-- navigation BOF -->
<?php $rootMenus = $this->getRootMenu(); ?>
<div class="mt-menu mt-effect-slide">
    <div class="mt-menu-active">
        <div class="navbar-header">
            <div class="navbar-toggle" type="button" data-toggle="collapse">
                <div class="collapsed-icon pull-left">
                    <span class="sr-only"><?php echo $this->__('Navigation');?></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </div>
                <span class="title-canvas"><?php echo $this->__('Menu');?></span>
                <button type="button" class="mt-close-canvas"></button>
            </div>
        </div>
    </div>
    <div class="sidebar">
        <ul id="mt_accordionmenu" class="nav-accordion nav-mobile-accordion">
            <?php foreach($rootMenus as $drillMenu): ?>
                <?php echo $this->getLayout()->createBlock($this->getType($drillMenu->getType())->getBlock())->setMenu($drillMenu)->drawDrillItem() ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<div class="site-overlay"></div>
