<?php
/******************************************************
 * @package Megamenu module for Magento 1.4.x.x and Magento 1.5.x.x
 * @version 1.5.0.4
 * @author http://www.9magentothemes.com
 * @copyright (C) 2011- 9MagentoThemes.Com
 * @license PHP files are GNU/GPL
*******************************************************/
?>
<?php if(Mage::helper('megamenu')->isActive()): ?>
<?php $rootMenus = $this->getRootMenu(); ?>
<div class="menu-top container hidden-xs">
	<div class="megamenu-container">
		<div id="megamenu">
			<ul id="mt_megamenu">
				<?php foreach($rootMenus as $rootMenu): ?>
				    <?php echo $this->getLayout()->createBlock($this->getType($rootMenu->getType())->getBlock())->setMenu($rootMenu)->drawItem() ?>
				<?php endforeach; ?>
				<li>
					<div class="background">
						<div class="left>"></div>
					</div>
				</li>
			</ul>
		</div>
	</div>
</div>
<script type="text/javascript">
//<!CDATA[
    megamenuObject = {};
    megamenuObject.Transitions = 'Effect.Transitions.backOut';
    megamenuObject.Effect = '<?php echo Mage::helper('megamenu')->isActiveFancy() ?>';
    megamenuObject.Duration = '<?php echo Mage::helper('megamenu')->getDuration() ?>';
//]>
</script>
<?php endif; ?>