<?php
/**
 * @category    MT
 * @package     MT_Collection
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<div class="page-title collection-view">
    <h1 class="utm-cookies"><?php echo $this->getTitle()?></h1>
</div>
<?php echo $this->getChildHtml('collection.list')?>