<?php
/**
 * @category    MT
 * @package     MT_KidsPlaza
 * @copyright   Copyright (C) 2014 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php /* @var $this MT_KidsPlaza_Block_Catalog_Product_Videos */ ?>
<?php $videos = $this->getVideos() ?>
<?php if (count($videos)): ?>
<div id="product-videos" class="hidden-xs">
    <script type="text/javascript">
        (function(){
            var script = document.createElement('script');
            script.src = 'https://www.youtube.com/iframe_api';
            var firstScriptTag = document.getElementsByTagName('script')[0];
            firstScriptTag.parentNode.insertBefore(script, firstScriptTag);
        })();
        var YTPlayer, YTVideoCount=0, YTVideoTotal=0;
        function onYouTubeIframeAPIReady(){
            YTPlayer = new YT.Player('player', {
                height: 390,
                width: 640,
                playerVars: {wmode: 'transparent'},
                videoId: '<?php echo current($videos) ?>'
            });
        }
        function getYoutubeVideoInfo(videoId){
            var firstScriptTag = document.getElementsByTagName('script')[0],
                script = document.createElement('script'),
                urlAPI = 'https://gdata.youtube.com/feeds/api/videos/' + videoId +
                '?v=2&alt=json-in-script&callback=onYoutubeVideoInfoCallback';

            script.src = urlAPI;
            firstScriptTag.parentNode.insertBefore(script, firstScriptTag);
        }
        function onYoutubeVideoInfoCallback(data){
            try{
                var thumb = data['entry']['media$group']['media$thumbnail'][0]['url'],
                    title = data['entry']['title']['$t'],
                    desc = data['entry']['media$group']['media$description']['$t'],
                    user = data['entry']['author'][0]['name']['$t'],
                    itemElm = document.createElement('div'),
                    imgElm = document.createElement('img'),
                    infoElm = document.createElement('div'),
                    titleElm = document.createElement('a'),
                    descElm = document.createElement('div'),
                    userElm = document.createElement('div'),
                    listElm = document.getElementById('video-list');

                itemElm.className = 'video-item';
                infoElm.className = 'video-item-info';
                titleElm.className = 'video-item-title';
                titleElm.href = 'javascript:void(0)';
                descElm.className = 'video-item-desc';
                userElm.className = 'video-item-user';

                titleElm.innerHTML = title;
                descElm.innerHTML = jsTruncate(desc, 100);
                userElm.innerHTML = '<i class="glyphicon glyphicon-user"></i> ' + user;
                imgElm.src = thumb;

                var videoId = data['entry']['id']['$t'].split(':')[3];
                imgElm.onclick = onYoutubeVideoClick.bind(this, videoId);
                titleElm.onclick = onYoutubeVideoClick.bind(this, videoId);

                infoElm.appendChild(titleElm);
                infoElm.appendChild(descElm);
                infoElm.appendChild(userElm);
                itemElm.appendChild(imgElm);
                itemElm.appendChild(infoElm);
                listElm.appendChild(itemElm);

                YTVideoCount++;

                if (YTVideoCount == YTVideoTotal && window.jQuery && window.jQuery.fn.mCustomScrollbar){
                    jQuery(listElm).mCustomScrollbar({
                        scrollInertia: 0,
                        theme: 'dark-thin',
                        set_height: 390,
                        mouseWheel: true
                    });
                }
            }catch (e){}
        }
        function onYoutubeVideoClick(videoId){
            if (!YTPlayer) return;
            YTPlayer.loadVideoById(videoId);
        }
        function jsTruncate(input, length){
            if (!input || !length) return input;
            var output = input.substr(0, length);
            return output.substr(0, Math.min(output.length, output.lastIndexOf(' ')))+'...';
        }
        YTVideoTotal = <?php echo count($videos) ?>;
        <?php foreach ($videos as $video): ?>
        getYoutubeVideoInfo('<?php echo $video ?>');
        <?php endforeach ?>
    </script>
    <h3><?php echo $this->__('Product Videos') ?></h3>
    <div class="videos-wrapper hidden-xs">
        <div class="videos-wrapper-inner">
            <div class="video-inner">
                <div class="row">
                    <div class="video-content col-lg-7 col-md-9 col-sm-12  col-xs-12">
                        <div id="player"></div>
                    </div>
                    <div class="video-list col-lg-5 col-md-3 col-sm-12 col-xs-12" id="video-list"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif ?>