<?php
$questions = $this->_collection;
?>
<div class="mt-questions-main">
    <?php if ($questions->getSize()): ?>
    <ul class="media-list">
        <?php foreach($questions as $question){?>
        <li class="media">
            <span class="img pull-left">
                 <img src="<?php echo $this->getSkinUrl().'images/list_avatar_answer.png'?>"/>
            </span>
            <div class="media-body">
                <span class="title">
                    <?php echo $this->__('From') ?> <b><?php echo $this->escapeHtml($question->getQuestionAuthorName()) ?></b>
                </span>
                <p><?php echo $this->escapeHtml($question->getQuestionText()) ?></p>
                <p> <?php echo $this->__('At');?> <span class="date"><?php echo $this->formatDate($question->getQuestionDate()) ?> <?php echo $this->formatTime($question->getQuestionDate()) ?></span></p>
            </div>
        </li>
        <?php }?>
    </ul>
    <?php echo $this->getChildHtml('productquestions_pager'); ?>
    <?php else: ?>
    <p><?php echo $this->__('No answer'); ?></p>
    <?php endif; ?>
</div>