<?php
$session = Mage::getSingleton('core/session');
$helper = Mage::helper('productquestions');
$helper->generateCaptchaKey();
?>
<div class="form-question">
    <h3><?php echo Mage::helper('productquestions')->__('Question Form');?></h3>
    <form action="<?php echo $this->getAction();?>" id="mt-question-form" method="post">
        <div class="form-field form-group">
            <label for="question_author_name_field" class="required"><?php echo Mage::helper('productquestions')->__('Name (will be displayed on site)') ?><em>*</em></label><br />
            <input class="form-control required-entry" name="question_author_name" id="question_author_name_field" type="text" value="<?php echo $this->htmlEscape($this->getQuestionAuthorName()) ?>" placeholder="<?php echo $this->__('Enter name');?>"/>
        </div>
        <div class="form-field form-group">
            <label for="question_author_email_field" class="required"><?php echo Mage::helper('productquestions')->__('Email (will NOT be displayed on site)') ?><em>*</em></label><br />
            <input class="form-control required-entry validate-email" name="question_author_email" id="question_author_email_field" type="text" value="<?php echo $this->htmlEscape($this->getQuestionAuthorEmail()) ?>" placeholder="<?php echo Mage::helper('productquestions')->__('Enter email');?>" />
        </div>
        <div class="form-field form-group">
            <label for="question_author_email_field" class="required"><?php echo Mage::helper('productquestions')->__('Categories') ?><em>*</em></label><br />
            <select class="form-control" name="category_id">
                <option value=""><?php echo Mage::helper('productquestions')->__('Select');?></option>
                <?php foreach($this->getCategories() as $category) {?>
                    <option value="<?php echo $category->getCatId();?>"><?php echo $category->getName();?></option>
                <?php }?>
            </select>
        </div>
        <div class="form-field form-group">
            <label for="question_author_captcha_field" class="required"><?php echo Mage::helper('productquestions')->__('Captcha') ?><em>*</em></label><br />
            <?php echo $helper->displayCaptcha();?>
        </div>
        <div class="form-field form-group">
            <label for="question_text_field" class="required"><?php echo Mage::helper('productquestions')->__('Question') ?><em>*</em></label><br />
            <textarea class="form-control required-entry" name="question_text" id="question_text_field" cols="53" rows="10" placeholder="<?php echo Mage::helper('productquestions')->__('Enter your questions');?>"><?php echo $this->escapeHtml($data->getQuestionText()) ?></textarea>
        </div>
        <div class="button-set form-group">
            <button class="button btn-kid pull-right" type="submit"><span><?php echo Mage::helper('productquestions')->__('Submit question') ?></span></button>
        </div>
    </form>
</div>
