<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_ProductQuestions
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
?>
<?php if($this->getQuestionData()->getQuestionId()): ?>
<div class="product-question">
    <div class="main row">
        <div class="col-lg-12 media">
            <span class="img pull-left">
                 <img src="<?php echo $this->getSkinUrl().'images/list_avatar_question.png'?>"/>
            </span>
            <div class="media-body">
                <span class="title">
                    <?php echo $this->__('From') ?> <b><?php echo $this->getQuestionData()->getQuestionAuthorName() ?></b> at <span class="date"><?php echo $this->formatDate($this->getQuestionData()->getQuestionDate()) ?> <?php echo $this->formatTime($this->getQuestionData()->getQuestionDate()) ?></span>
                </span>
                <p><?php echo $this->getQuestionData()->getQuestionText();?></p>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="numb-answer">
                <?php echo $this->__('Answers: (%s)', $this->getCountAnswers());?>
            </div>
            <div class="form-answer">
                <?php echo $this->getChildHtml('answers_form'); ?>
            </div>
            <?php echo $this->getChildHtml('mainanswers'); ?>
        </div>
    </div>
</div>
<?php endif; ?>
