<?php
$questions = $this->_collection;
?>
<div class="mt-questions-main">
    <div class="quick-question">
        <div class="createquestion">
            <form id="mt-question-form" action="<?php echo $this->getAction();?>" method="post">
                <div class="inputwrapper">
                    <input type="text" name="question_text" id="question_text" value="<?php echo $this->escapeHtml($this->getQuestionText()) ?>" placeholder="<?php echo Mage::helper('productquestions')->__('what is your question?');?>">
                    <input class="btn-kid btn" type="submit" value="<?php echo Mage::helper('productquestions')->__('Question');?>" name="submitquestion" id="submitquestion">
                </div>
            </form>
        </div>
    </div>
    <?php if ($questions->getSize()): ?>
    <?php echo $this->getChildHtml('productquestions_pager'); ?>
    <ul class="media-list">
        <?php foreach($questions as $question){?>
        <li class="media">
            <div class="media-body row">
                <div class="col-lg-10 media">
                    <span class="img pull-left">
                         <img src="<?php echo $this->getSkinUrl().'images/list_avatar_question.png'?>"/>
                    </span>
                    <p>
                        <a href=<?php echo $this->getQuestionUrl($question->getQuestionId());?>><?php echo $this->escapeHtml($question->getQuestionText()) ?></a>
                    </p>
                    <span class="title">
                        <?php echo Mage::helper('productquestions')->__('From') ?> <b><?php echo $this->escapeHtml($question->getQuestionAuthorName()) ?></b>
                        <span class="category">
                            <?php echo Mage::helper('productquestions')->__('Question by');?>
                            <a href="<?php echo $this->getCategoryUrl($question->getCategoryId());?>"> <?php echo $this->questionByCategory($question->getCategoryId())->getName();?></a>
                        </span>
                        <span class="date">
                            <?php echo $this->formatDate($question->getQuestionDate()) ?>
                            <?php echo $this->formatTime($question->getQuestionDate()) ?>
                        </span>
                    </span>
                </div>
                <div class="col-lg-2">
                    <span class="answer pull-left"><?php echo Mage::helper('productquestions')->__('Answers: (%s)', $this->countAnswers($question->getQuestionId()));?></span>
                    <span class="viewed pull-left"><?php echo Mage::helper('productquestions')->__('View (%s)', $question->getHits());?></span>
                    <span class="link-answer pull-left">
                        <a href=<?php echo $this->getQuestionUrl($question->getQuestionId());?>>
                            <?php echo Mage::helper('productquestions')->__('Answer this question');?>
                        </a>
                    </span>
                </div>
            </div>
        </li>
        <?php }?>
    </ul>
    <?php else: ?>
    <p><?php echo Mage::helper('productquestions')->__('No questions asked yet'); ?></p>
    <?php endif; ?>
</div>