<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Review
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
?>
<?php $_items = $this->getCommentsCollection(); ?>
<?php if(count($_items)):?>
<div class="main-comments">
    <ul class="comments-list">
    <?php foreach($_items as $_item){?>
        <li class="media">
            <span class="img pull-left">
                 <img src="<?php echo $this->getSkinUrl().'images/list_avatar_question.png'?>"/>
            </span>
            <div class="media-body">
                <span class="main-review">
                    <span class="created_by">
                        <?php echo $this->__('<span class="created">%s</span>', $this->escapeHtml($_item->getCustomerName())) ?>
                        <small class="date"><?php echo $this->__('(Posted on %s)', $this->formatDate($_item->getCreatedAt()), 'long') ?></small>
                    </span>
                </span>
                <span class="review-detail"><?php echo nl2br($this->escapeHtml($_item->getComments())) ?></span>
            </div>
        </li>
    <?php }?>
    </ul>
</div>
<script type="text/javascript">
    dataComment = {};
    dataComment.pathUrl = '<?php echo $this->getSkinUrl().'images/list_avatar_question.png'?>';
</script>
<?php endif;?>

