<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Review
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
$storeName = Mage::app()->getStore()->getName();
?>
<?php
if($this->getCollection()){
    $_items = $this->getCollection();
}else{
    $_items = $this->getCommentsCollection();
}
?>
<?php if(count($_items)):?>
    <?php $i= 0; foreach($_items as $_item){?>
        <?php if ($i<=3){?>
        <li class="media">
            <span class="img pull-left">
                 <img src="<?php echo Mage::helper('kidsplaza')->avatar($_item->getCustomerName()) ?>"/>
            </span>
            <div class="media-body">
                <span class="main-review">
                    <span class="created_by">
                        <span class="created">
                            <?php echo $this->escapeHtml($_item->getCustomerName()); ?>
                            <?php if($_item->getAuthorType() == 'admin'){?>
                                <i>(<?php echo Mage::helper('mtreview')->__('By admin');?>)</i>
                            <?php }?>
                        </span>
                        <small class="date"><?php echo Mage::getModel('core/store')->load($_item->getStoreId())->getName();?>, <?php echo $this->getFormatDate($_item->getCreatedAt());?> - <?php echo $this->__('About %s ago',$this->getTimeFormat($_item->getCreatedAt()));?></small>
                    </span>
                </span>
                <span class="review-detail"><?php echo nl2br($this->escapeHtml($_item->getComments())) ?></span>
            </div>
        </li>
        <?php }?>
    <?php $i++; }?>
        <?php if(count($_items)>4):?>
        <li class="comments-more">
            <span class="loading"><?php echo $this->__('Loading...');?></span>
            <a onclick="return showMoreComments(this,'<?php echo $this->getReviewId();?>');"> <?php echo Mage::helper('mtreview')->__('Show more comments');?></a>
        </li>
        <?php endif;?>
<?php endif;?>

