<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<?php $comments = $this->getComments() ?>
<?php if (count($comments) > 0): ?>
	<ul class="comment-list<?php if ($this->getParentId()): ?> children<?php endif; ?>">
		<?php foreach($comments as $comment): ?>
			<li class="comment media" id="comment-<?php echo $comment->getId() ?>">
                <?php if ($avatarUrl = $comment->getAvatarUrl(50)): ?>
                    <div class="gravatar pull-left">
                        <img src="<?php echo $avatarUrl ?>" alt="<?php echo $this->escapeHtml($comment->getCommentAuthor()) ?>" />
                    </div>
                <?php endif; ?>
				<div class="media-body">
					<div class="comment-meta comment-date by">
						<?php if ($comment->getCommentAuthorUrl() !== '#'): ?>
							<a href="<?php echo $this->escapeHtml($comment->getCommentAuthorUrl()) ?>" rel="nofollow" class="comment-url"><?php echo $this->escapeHtml($comment->getCommentAuthor()) ?></a>
						<?php else: ?>
							<span class="comment-url">
								<?php echo $this->escapeHtml($comment->getCommentAuthor()) ?>
							</span>
						<?php endif; ?>
						<?php echo $this->__('%s - %s', date('d/m/Y', strtotime($comment->getCommentDate())) , $comment->getCommentTime()) ?>
					</div>
					<span class="comment-entry entry"><?php echo $this->getCommentContent($comment) ?></span>
				</div>
				<?php echo $this->getChildrenCommentsHtml($comment) ?>
			</li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>