<?php
/**
 * @category    MT
 * @package     MT_Point
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php echo $this->getChildHtml('mtpoint_balance')?>
<?php echo $this->getChildHtml('mtpoint_manage')?>
<?php echo $this->getChildHtml('mtpoint_history')?>