<?php
/**
 * @category    MT
 * @package     MT_KidsPlaza
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
/** @var MT_KidsPlaza_Block_Catalog_View $this */
$_category = $this->getCategory();
?>
<div class="category-products root-category">
    <?php $column = 5 ?>
    <?php $categories = $_category->getChildrenCategories() ?>
    <?php $i=0;foreach ($categories as $c): ?>
        <?php /** @var $c Mage_Catalog_Model_Category */ ?>
        <?php $c->load($c->getId(), array('image')) ?>
        <?php if ($i++ % $column === 0): ?>
            <ul class="grid-5 products-grid">
        <?php endif ?>
        <li class="item">
            <a class="product-image" href="<?php echo $c->getUrl() ?>">
                <img src="<?php echo Mage::helper('kidsplaza')->resize(Mage::getBaseDir('media').DS.'catalog'.DS.'category'.DS.$c->getImage(), 135) ?>"/>
            </a>
            <h2 class="product-name">
                <a href="<?php echo $c->getUrl() ?>"><?php echo $c->getName() ?></a>
            </h2>
        </li>
        <?php if ($i % $column === 0 || $i == count($categories)): ?>
            </ul>
        <?php endif ?>
    <?php endforeach ?>
</div>