<?php if($this->getCollection()->getSize()): ?>
    <div class="toolbar" role="toolbar">
        <div class="btn-group toolbar-limit">
            <a class="btn btn-default" href="javascript:void(0)">
                <?php if($this->getLastPageNum()>1): ?>
                    <?php echo $this->__('%s - %s / %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                <?php else: ?>
                    <?php echo $this->__('%s / %s', $this->getTotalNum(), $this->getTotalNum()) ?>
                <?php endif; ?>
            </a>
            <span class="btn-group">
                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" type="button">
                    <?php echo $this->__('Limit') ?>&nbsp;<?php echo $this->getLimit()?>&nbsp;<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                        <li><a href="<?php echo $this->getLimitUrl($_key) ?>"><?php echo $_limit ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </span>
        </div>

        <?php if($this->getLastPageNum()>1): ?>
        <div class="btn-group toolbar-pages">
            <?php if (!$this->isFirstPage()): ?>
                <a class="btn btn-default previous<?php if(!$this->getAnchorTextForPrevious()): ?> i-previous<?php endif;?>" href="<?php echo $this->getPreviousPageUrl() ?>" title="<?php echo $this->__('Previous') ?>">
                    <?php echo $this->__('<') ?>
                </a>
            <?php endif;?>

            <?php if ($this->canShowFirst()): ?>
                <a class="btn btn-default first" href="<?php echo $this->getFirstPageUrl() ?>">1</a>
            <?php endif;?>

            <?php if ($this->canShowPreviousJump()): ?>
                <a class="btn btn-default previous_jump" title="" href="<?php echo $this->getPreviousJumpUrl() ?>">...</a>
            <?php endif;?>

            <?php foreach ($this->getFramePages() as $_page): ?>
                <?php if ($this->isPageCurrent($_page)): ?>
                    <a class="btn btn-default active"><?php echo $_page ?></a>
                <?php else: ?>
                    <a class="btn btn-default " href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a>
                <?php endif;?>
            <?php endforeach;?>


            <?php if ($this->canShowNextJump()): ?>
                <a class="btn btn-default next_jump" title="" href="<?php echo $this->getNextJumpUrl() ?>">...</a>
            <?php endif;?>

            <?php if ($this->canShowLast()): ?>
              <a class="btn btn-default last" href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a>
            <?php endif;?>

            <?php if (!$this->isLastPage()): ?>
                <a class="btn btn-default next<?php if(!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?>" href="<?php echo $this->getNextPageUrl() ?>" title="<?php echo $this->__('Next') ?>">
                     <?php echo $this->__('>') ?>
                </a>
            <?php endif;?>
            </ol>

        </div>
        <?php endif; ?>
    </div>
<?php endif ?>
